#TODO:                           Check windows environment build
version: 1.0.{build}

branches:

  only:

  - main

build:

  parallel: true

  verbosity: detailed
environment:
  matrix:
  - GENERATOR: "Visual Studio 16 2019"
    ARCH: 32
  - GENERATOR: "Visual Studio 16 2019 -A x64"
    ARCH: 64
  - GENERATOR: "MSYS Makefiles"
    ARCH: 32
  - GENERATOR: "MSYS Makefiles"
    ARCH: i686 # this is for 32-bit MinGW-w64
  - GENERATOR: "MSYS Makefiles"
    ARCH: 64

init:
  - appveyor version

install:
  - cmd: cd C:\Tools\vcpkg
  - cmd: git pull
  - cmd: .\bootstrap-vcpkg.bat
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: vcpkg install sqlite3:x64-windows
  - cmd: vcpkg integrate install
  - cmd: vcpkg list
  - cmd: cd %APPVEYOR_BUILD_FOLDER%

cache:
- i686-4.9.2-release-win32-sjlj-rt_v3-rev1.7z
- x86_64-4.9.2-release-win32-seh-rt_v3-rev1.7z
- c:\tools\vcpkg\installed\

build_script:
- ps: |
    if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
      throw "There are newer queued builds for this pull request, failing early." }
    mkdir build
    cd build
    if ($env:GENERATOR -ne "MSYS Makefiles") {
      cmake -G"$env:GENERATOR" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DINSTALL_DEPENDENCIES=ON -DUNIT_TESTS=ON -DINSTALL_EXAMPLES=ON -DINSTALL_DOCS=ON ..
      cmake --build .
      cmake --install .
    }
- cmd: |
    if "%GENERATOR%"=="MSYS Makefiles" (C:\MinGW\msys\1.0\bin\sh --login /c/projects/Sqlite3Utils/scripts/appveyor-mingw.sh)
test_script:
- ps: ctest -V .
