os: linux
dist: xenial
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
      - sqlite3
script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  # Create dir for build files
  - mkdir build && cd build/
  # Run cmake default way
  - cmake ..
  # Then build the project
  - cmake --build .
  # Run the tests
  - ctest --progress --verbose
  # Then install the project
  - cmake --install .
