name: C/C++ CI

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
  schedule:
    - cron: "0 2 * * 1-5"
      
  workflow_dispatch:
 

jobs:
  
  set_environment:
    
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: Setup C++ environment
        # You may pin to the exact commit or the version.
        # uses: kurocha/setup-cpp@ef637353b9bec350da9c1088b73d2217d2441696
        uses: kurocha/setup-cpp@v1


  build_ubuntu:
    needs: [set_environment]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Installing handler
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/AEduardo-png/dbHandler-sqlite3.git
          cd dbHandler-sqlite3
            
      - name: Install Dependencies
        run: |
          sudo apt-get install sqlite3
          
      - name: Build Solution
        run: |
          cd source
          make      
      
  cppcheck:
    needs: [set_environment, build_ubuntu]
    runs-on: ubuntu-latest
    
    steps:
    - name: cppcheck-action
      # You may pin to the exact commit or the version.
      # uses: deep5050/cppcheck-action@1c1883644278ced5cc18c37e32eb26337e340a9e
      uses: deep5050/cppcheck-action@v1.2
      
